### ISSUE TITLE
building elevations machine learning number of floors

### ISSUE THREAD

**Issue by buildvoc10** [maikpaixao/intelligent-housing-porfolio-optmization#1] opened 2023-07-25 16:41 UTC
Hello was wondering if you had used machine learning to recognise number of floors in a building using images?

**Comment by RAGHAV-N5** [comment] 2023-07-26 14:57
I particularly haven't used it but it can be a great project to work on.
Yes, it is possible to recognize the number of floors in a building using images in Machine Learning techniques, especially if you have relevant data and features that can help with the prediction. However, it's essential to understand that this task might be challenging, and the accuracy of the prediction will depend on the quality of data and the features used.

Here's a high-level overview of how you could approach this task using Machine Learning:

Data Collection: Gather a dataset that contains information about buildings and their corresponding number of floors. This dataset should have labeled data where the number of floors is the target variable.

Feature Engineering: Extract relevant features from the data that could help in predicting the number of floors. Possible features could include the building's height, area, construction year, location, and any other relevant information.

Data Preprocessing: Clean the data, handle missing values, and normalize or scale the features as needed to prepare the data for training.

Model Selection: Choose an appropriate Machine Learning model for regression since we are predicting a continuous value (number of floors). Common models for regression tasks include Linear Regression, Decision Trees, Random Forests, Support Vector Machines (SVM), or even more advanced models like Gradient Boosting or Neural Networks.

Model Training: Split the data into training and testing sets. Train the selected model on the training data using the features to predict the number of floors.

Model Evaluation: Evaluate the trained model on the test data using appropriate metrics like Mean Absolute Error (MAE), Mean Squared Error (MSE), or Root Mean Squared Error (RMSE).

Model Fine-Tuning: Depending on the model's performance, you can experiment with hyperparameter tuning or try different feature combinations to improve the prediction accuracy.

Deployment: Once you have a satisfactory model, you can deploy it to make predictions on new buildings with unknown floor counts.

Keep in mind that predicting the number of floors in a building based solely on some features might not always be highly accurate due to various factors affecting building characteristics. However, with sufficient data and well-chosen features, Machine Learning models can provide reasonably good predictions for this task.

**Comment by maikpaixao** [comment] 2024-03-10 12:23
Hi @buildvoc10 , I've not used images to capture the number of floors in a building to develop this dataset.

**Comment by maikpaixao** [comment] 2024-03-10 12:25
For now, I'm going to close this issue, but feel free to reach out if you have any more questions.

**Closed as completed by maikpaixao** 2024-03-10 12:25 UTC
